### PR TITLE
import boolean from prim

### PR DESCRIPTION
**Pull request by justinwoo**
I guess this will be in some upcoming 0.12.x release https://github.com/purescript/purescript/pull/3389

So this cannot be merged for 0.12.1 but sometime after

### CODE REVIEW

**Comment by justinwoo** [comment]
Relevant referrers of typelevel-prelude:

```
"foreign-object"
"react"
"react-basic"
"record"
"record-format"
"simple-json"
"typelevel"
"variant"
```

justinwoo

```
"choco-pie"
"expect-inferred"
"jajanmen"
"kancho"
"milkis"
"record-extra"
"tortellini"
"type-isequal"
```

**Comment by hdgarrood** [comment]
I suppose this is reallya breaking change then, since we are dropping support for 0.12.1 and below? Perhaps we should wait a little bit and see if there are any other breaking changes we’d like to do at the same time?

**Comment by justinwoo** [comment]
Yeah, I think this should be a new major release but it won't require consumers to do more than upgrade the library version they use. I don't think there are any other changes queued up though?

**Comment by hdgarrood** [comment]
I take that back, we'd need https://github.com/purescript/purescript/issues/3391 to be able to address #43 sensibly.

**Comment by justinwoo** [comment]
Will someone merge this sometime?

**Comment by LiamGoodacre** [comment]
Thanks @justinwoo

**Comment by justinwoo** [comment]
thanks!

**Pull request merged**
