### PR TITLE
Added RowLabels type class.

### PR DESCRIPTION
**Pull request by coot**
```
labels :: forall l. RowLables l => RLProxy r -> Array String
labelsR :: forall r l. RowToList r l => RowLables l => RProxy r -> Array String
```

Promissed PR as discussed in https://github.com/purescript/purescript-record/pull/6
I think we could use `pushd` via ffi instead of `cons x xs = [x] <> xs` hack.

### CODE REVIEW

**Comment by paf31** [comment]
I agree, it might be nice to try to improve the performance here a bit. We could add a builder api to `arrays`, or maybe it could just be as simple as specializing this for some small values of n.

**Comment by coot** [comment]
Or maybe using your approach with `ST` monad.  I added `Array String` instance which does the same as the `RowLabels` class in this PR.
http://try.purescript.org/?backend=core&gist=c8ff61154249d081f0e02c5516cbbb0f&session=a31a408c-55de-0d53-8e9b-f55307b32d9b

**Comment by coot** [comment]
Maybe the way forward is to have a `RowLabels` (optimised by speciallising up to 10 arguments) and the `ST` builder published somewhere (in `Control.Module.ST.Builder` in `purescript-st` or in a new package).

**Comment by coot** [comment]
`RowLabels` at some point can be optimized by the compiler, since all the information is static, then there is no need for the `ST` builder.

**Comment by paf31** [comment]
Yes, let's try that.

**Comment by coot** [comment]
If you want the ST stuff in purescript-contrib you'll need to create a repo for that. I can maintain it.

**Comment by coot** [comment]
I added test (in the prelude style in `Unit -> Unit` monad).  Seems there is an issue with the development version of the compiler (the only one I tried).  It takes too much time to compile the test file:
```
time purs compile ...
Compiling Test.Main
purs compile 'bower_components/purescript-*/src/**/*.purs' 'src/**/*.purs'   41.16s user 13.72s system 368% cpu 14.880 total
```

```
time pulp test
* Building project in /home/marcin/repos/purescript/purescript-typelevel-prelude
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
* Running tests...
* Tests OK.
pulp test  43.16s user 11.92s system 360% cpu 15.283 total
```

**Comment by paf31** [comment]
@coot Thanks!

@LiamGoodacre What do you think of the unrolled loop idea?

**Comment by LiamGoodacre** [comment]
I'm okay-ish with the unrolling - at least, in the absence of compiler optimisations.  However, I'm wondering if we should build a `List` instead of an `Array`?  If the issue is specifically that arrays have poor cons perf.

**Comment by paf31** [comment]
I think that would be fine too, but I'm also a little concerned that we'll have one dictionary lookup and function call per label.

**Pull request closed without merging**
