### PR TITLE
Add SubRow class

### PR DESCRIPTION
**Pull request by coot**
I need `SubRow` class for: https://github.com/purescript/purescript-record/issues/5

### CODE REVIEW

**Comment by paf31** [comment]
Why not use `Union` directly? This class doesn't add any new laws or behavior.

**Comment by coot** [comment]
good point, indeed.

**Comment by matthewleon** [comment]
I feel like this has ergonomic value to library users: it requires one less variable definition in your `forall`, and it somewhat clarifies your intentions. One place I would find this useful, for example, is in replacing use of `Options` from `purescript-options` with a simple `SubRow r OptionsRow`.

It's a bit more readable than `Union r r' OptionsRow`.

**Comment by matthewleon** [comment]
Here is an example of what I'm going for. I really think `SubRow` makes this much more readable: http://try.purescript.org/?session=062a58b9-1bb1-b95d-2feb-b40bf47814b1

**Pull request closed without merging**
