### PR TITLE
typeclass instances for proxies

### PR DESCRIPTION
**Pull request by matthewleon**
These are copied from the instances for `Proxy`.

### CODE REVIEW

**Comment by matthewleon** [comment]
I'm using an `Eq` instance here: https://github.com/matthewleon/purescript-nat-kind/blob/master/test/Main.purs

It's a fork of another library, along with its test suite, so there might be a better way to do this. But I think these instances make sense.

**Comment by LiamGoodacre** [comment]
I'm happy for these to be added.  But for your test: isn't it only about if they type check (i.e, before the test even runs), so you could do something like:
```
typeEqual :: forall e a. a -> a -> Test e
typeEqual _ _ = success

tests = do
  suite "trich" do
    test "2 < 3" do
      typeEqual (OProxy :: OProxy LT) $ trich d2 d3
```

**Comment by matthewleon** [comment]
Yes, I think you're absolutely right. I realized that as I wrote the PR... But felt the instances do make sense regardless.

**Comment by kl0tl** [comment]
We‘ve deprecated the monomorphic proxies in favor of Type.Proxy.Proxy, which we’ll be polymorphic in v0.14, I think we should close this.

**Pull request closed without merging**
