### PR TITLE
RowList operations

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Building up a collection of RowList operations.  PR for discussion.

### CODE REVIEW

**Comment by MonoidMusician** [comment]
Do you want to add a `UnionNub` kind of thing for properly typing `merge`? (as in [RowUnion.purs](https://github.com/purescript/purescript/blob/master/examples/passing/RowUnion.purs), which should be left-biased unique but only has a `Union` constraint which creates duplicates)

Here's a naïve implementation (left-biased):
```purescript
class UnionNub
  (a :: # Type)
  (b :: # Type)
  (c :: # Type)
  | -> a b c
instance unionNub ::
  ( Union a b r
  , RowToList r rl
  , ListToRow rl r
  , RowListNub rl cl
  , ListToRow cl c
  ) => UnionNub a b c
```

I could probably draft up intersection and difference too.

**Comment by justinwoo** [comment]
Could this go in sometime so I can depend on it? 😄 I need to use the RowAppend class the most

**Comment by paf31** [comment]
I'm happy to merge this whenever @LiamGoodacre says it's good to go.

**Comment by LiamGoodacre** [comment]
Sorry, I completely forgot about this.

**Comment by LiamGoodacre** [comment]
I'll merge once Travis is happy.

**Comment by LiamGoodacre** [comment]
@paf31 do you want to make a v2.4.1 for this?

**Pull request merged**
